services:
  - type: web
    name: ai-social-media-content-tool
    runtime: docker
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: TINYMCE_API_KEY
        sync: false
