services:
  - type: web
    name: social-media-trending-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
    buildFilter:
      ignoredPaths:
        - "*.md"
        - "*.txt"
        - "*.json"
        - "*.yml"
        - "*.yaml"
        - "tests/"
        - "docs/"
