services:
  - type: web
    name: ai-social-media-content
    runtime: python
    plan: free
    rootDir: Downloads/social_media_trending_app
    buildCommand: pip install --upgrade pip && pip install -r requirements_clean.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    repo: https://github.com/Karehmaciu/social_media_trending_app.git
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: TINYMCE_API_KEY
        sync: false
