services:
  - type: web
    name: ai-social-media-content
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements_app.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    repo: https://github.com/Karehmaciu/social_media_app.git
    branch: main
    rootDir: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: TINYMCE_API_KEY
        sync: false
